---
title: "Costco Holiday Spending"
subtitle: "Predicting Costco members spending during the holiday season of 2025"
author: "Zeina Abudamous"
format:
  html:
    toc: true
    toc-depth: 3
    code-fold: true
    number-sections: true
    theme: flatly
---
```{r Library}
library(MCMCpack)
```

# Creating the Data

```{r}
set.seed(143)

# Number of members (rows)
n <- 5000
member_ID <- 1:n

# This will generate membership tenure values between 0 and 42 then rounds up a year. 
## the beta distribution is used instead of the uniform distribution because we want more members with longer tenures, which matches Costco's high renewal rate, where we make 20-42 year members the most common

member_tenure_years <- round(rbeta(n, 2, 1)*42, 1)

## Executive Members are more likely to have a longer tenure

## This means that members with about 
## a 5 year tenure have a 50% chance of being members,
## < 5 year are mostly non exec. members
## 10 to 15 years have a high chance of being executives and 
## 20+ years are almost always executive members
## This code centers the executive member probability around 5 years of membership tenure and controls how steeply the probability increases
executive_flag <- rbinom(n, 1, plogis((member_tenure_years - 5) / 5))

### Member Behavior for each member over the last 12 & 24 months

### this is the total dollar amount spent in the last 12 mo, where exec. members. generally spend more than none-exec members.
### the gamma distribution is being used as it is ideal for + value only data, and for sight-skewed spending (mostly moderate spenders)
rolling_12mo_spend <- rgamma(n, shape = 5 + executive_flag*2, rate = 1/700)

### total amount of dollars spent in the last 2 years
### we are adding this total to the previous total of 1 year to make sure the numbers generated for the 2 year spend are > than the ones for 1 year spend
rolling_24mo_spend <- rolling_12mo_spend + rgamma(n, shape = 3, rate = 1/900)

### Total 12 month visits
### This generates the number of warehouse visits per year for each member using the poisson distribution, which is preferred for count data and visits/evens data.
### the difference between the number of visits for members and non-members is small
rolling_12mo_visit <- rpois(n, lambda = 20 + executive_flag * 3)

### Basket size

### This calculates the AVERAGE dollars spent per visit in the last year
### This makes it possible to see whether each member does less frequent large trips or more frequent small ones.
### We also use the pmax(rolling_12_month_visits, 1) part to prevent division by zero
rolling_12mo_avg_basket <- rolling_12mo_spend/pmax(rolling_12mo_visit, 1)

#### Spending across departments
base_alpha <- c(
  grocery_consumables = 5.5,
  pharmacy_health = 2.0,
  home_hardware = 2.5,
  auto_sporting = 1.5,
  general_merch = 3.5
)

#### Seasonal Uplift
seasonal_uplift <- c(
  grocery_consumables = 0.8,
  pharmacy_health = 1.2, # Optical & hearing aid benefits
  home_hardware = 1.3,
  auto_sporting = 1.1,
  general_merch = 2.0
)

#### Seasonal alpha
seasonal_alpha <- base_alpha * seasonal_uplift

dept_mix <- rdirichlet(
  n = n,
  alpha = seasonal_alpha
)
dept_mix <- as.data.frame(dept_mix)
colnames(dept_mix) <- paste0("pct_spend_", names(seasonal_alpha))

##### Return rate
return_rate <- pmin(abs(rnorm(n, mean = 0.07 - member_tenure_years/300, sd = 0.03 )), 0.25)

##### Weekend shopping: 0.2 to 0.7
weekend_shopping_ratio <- runif(n, 0.2, 0.7)

##### Promo usage
##### we are assuming that executive members use promos more than non-executive members
promo_usage_rate <- pmin(runif(n, 0.05, 0.35) + executive_flag * 0.05, 0.5)

###### Holiday Spend: Target variable
###### How much did each member spend during the months of October to December
holiday_spend <- rolling_12mo_spend * runif(n, 0.15, 0.35) +
  200 * executive_flag +
  180 * dept_mix$pct_spend_general_merch +   # electronics, toys, clothing
  120 * dept_mix$pct_spend_home_hardware +   # housewares, home projects
  100 * dept_mix$pct_spend_pharmacy_health + # optical / hearing benefits
  rnorm(n, 0, 80)

# no negative values
holiday_spend <- pmax(holiday_spend, 20) 

####### Assembling the dataset
Costco_sim <- data.frame(
  member_ID,
  rolling_12mo_spend,
  rolling_12mo_visit,
  rolling_12mo_avg_basket,
  rolling_24mo_spend,
  
  pct_spend_grocery_consumables = dept_mix$pct_spend_grocery_consumables,
  pct_spend_pharmacy_health    = dept_mix$pct_spend_pharmacy_health,
  pct_spend_home_hardware      = dept_mix$pct_spend_home_hardware,
  pct_spend_auto_sporting      = dept_mix$pct_spend_auto_sporting,
  pct_spend_general_merch      = dept_mix$pct_spend_general_merch,
  
  member_tenure_years,
  return_rate,
  executive_flag,
  weekend_shopping_ratio,
  promo_usage_rate,
  holiday_spend
)

head(Costco_sim)
str(Costco_sim)
```

```{r}
# creating a csv file
write.csv(
  Costco_sim,
  "Costco_simulated_data.csv",
  row.names = FALSE
)
```


